// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BarEscolarMateriais.Models;

public partial class Historico
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal? Price { get; set; }

    public int Categoryid { get; set; }

    public int StockQuantidade { get; set; }

    public string Userid { get; set; }

    public int Materialid { get; set; }

    public virtual Material Material { get; set; }

    public virtual User User { get; set; }
}