// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BarEscolarMateriais.Models;

public partial class Material
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public int Categoryid { get; set; }

    public int? Stock { get; set; }

    public virtual MaterialCategory Category { get; set; }

    public virtual ICollection<Historico> Historicos { get; set; } = new List<Historico>();
}