// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BarEscolarMateriais.Models;

public partial class MenuDay
{
    public int Id { get; set; }

    public int? Menuweekid { get; set; }

    public DateOnly? Date { get; set; }

    public string Option { get; set; }

    public string MainDish { get; set; }

    public string Soup { get; set; }

    public string Dessert { get; set; }

    public string Notes { get; set; }

    public int? MaxSeats { get; set; }

    public virtual MenuWeek Menuweek { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}