// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BarEscolarMateriais.Models;

public partial class OrderItem
{
    public int Id { get; set; }

    public int? Orderid { get; set; }

    public int? Productid { get; set; }

    public bool? IsMenu { get; set; }

    public int? Quantity { get; set; }

    public DateOnly? CreatedAt { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal? Subtotal { get; set; }

    public int? Menuid { get; set; }

    public virtual Order Order { get; set; }

    public virtual MenuDay Product { get; set; }

    public virtual Product ProductNavigation { get; set; }
}