// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BarEscolarMateriais.Models;

public partial class Order
{
    public int Id { get; set; }

    public string Userid { get; set; }

    public decimal? Total { get; set; }

    public DateOnly? Createdat { get; set; }

    public bool? State { get; set; }

    public string Type { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual User User { get; set; }
}