// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BarEscolarMateriais.Models;

public partial class Product
{
    public decimal? Price { get; set; }

    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? CategoryId { get; set; }

    public int? Kcal { get; set; }

    public int? Protein { get; set; }

    public int? Fat { get; set; }

    public int? Carbs { get; set; }

    public int? Salt { get; set; }

    public string Allergens { get; set; }

    public int? Stock { get; set; }

    public bool? IsActive { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}